### ISSUE TITLE
oJalgo integration PR?

### ISSUE THREAD

**Issue by xornand** [mishadoff/numberto#7]
As mentioned BigInteger is probably not the most efficient method of performing numerical computation. I'm pondering forking a solution based on oJalgo (or JBLAS -- as in numerical analysis that's more of the defacto standard end-users would be comfortable with and performs fairly well as it FFI's to BLAS/LAPLAC which, with Intel MKL, works out to be darn tootin' fast). If I were to do so and submit a pull request, would you be likely to accept it? Would you be more likely to accept one or the other (i.e. oJalgo seems to be actively developed, but JBLAS would be more familiar for an end-user (though this should not matter as the consumer would be ignorant of the implementation details))?

Here are some unbiased 3rd party benchmarks maintained by 3rd party independent sources - http://lessthanoptimal.github.io/Java-Matrix-Benchmark/. Seems to be developed primarily by github user: @lessthanoptimal who doesn't seem to be affiliated with any of the projects. My independent (less than extensive, mind you) initial analysis is fairly well in-line with his results.

-A

**Comment by lessthanoptimal** [comment]
Just thought I would chime in.  I do have a library of my own in there, EJML, but I was in communication with most of the other library developers while  creating the benchmark tool.  The biggest bias (I think) in the benchmark is that it weights results from small matrices and very large ones equally.  Most developers focused on just large matrices. 

ojAlgo is now the fastest overall pure java library.  The author has put effort into rounding out its performance and now has a bunch of specialized code.  I would consider MTJ with native libraries over JBlas sure it is being actively developed and out performed it in the last full run. 

- Peter

**Comment by mishadoff** [comment]
What would be the goal of introducing ojAlgo? It should be transparent and without introducing complexity to the user. 
Almost every function in numberto is the self-contained example, which you can copy and play with it. We don't have any external dependencies, and the main goal for numberto to explain some algorithm, not focus on performance
